### ISSUE TITLE
FASTERDistributedCache is marked as internal

### ISSUE THREAD

**Issue by jodydonetti** [mgravell/FASTERCache#1]
Currently the `FASTERDistributedCache` is marked as internal, see [here](https://github.com/mgravell/FASTERCache/blob/d38fcfee43742802370908ee89e28d01f91dcb46/src/FASTERCache/FASTERDistributedCache.cs#L12).

Probably an oversight, but doublechecking in case I'm missing something.

**Comment by mgravell** [comment]
fixed (indirectly) via https://github.com/mgravell/FASTERCache/commit/cd5a5786a47db98cb7fc6f84b7657125f36bd104
